apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort   # or LOADBALANCER if NP not available
  selector:
    app: nodejs-frontend
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080 # optional, Kubernetes will assign one if omitted
